blinky.obj: ../blinky.c
blinky.obj: /opt/ti/flash/f/inc/hw_types.h
blinky.obj: /opt/ti/flash/f/inc/hw_memmap.h
blinky.obj: /opt/ti/flash/f/driverlib/fpu.h
blinky.obj: /opt/ti/flash/f/driverlib/sysctl.h
blinky.obj: /opt/ti/flash/f/driverlib/rom.h
blinky.obj: /opt/ti/flash/f/driverlib/gpio.h
blinky.obj: /opt/ti/flash/f/driverlib/pin_map.h
blinky.obj: ../buttons.h
blinky.obj: ../qs-logger.h
blinky.obj: ../usbstick.h
blinky.obj: /opt/ti/flash/f/inc/hw_gpio.h
blinky.obj: /opt/ti/flash/f/inc/hw_hibernate.h
blinky.obj: /opt/ti/flash/f/utils/ustdlib.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdarg.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/linkage.h
blinky.obj: /opt/ti/flash/f/inc/hw_sysctl.h
blinky.obj: /opt/ti/flash/f/driverlib/debug.h
blinky.obj: /opt/ti/flash/f/driverlib/adc.h
blinky.obj: /opt/ti/flash/f/driverlib/hibernate.h
blinky.obj: /opt/ti/flash/f/driverlib/systick.h
blinky.obj: /opt/ti/flash/f/grlib/grlib.h
blinky.obj: /opt/ti/flash/f/grlib/widget.h
blinky.obj: /opt/ti/flash/f/grlib/canvas.h
blinky.obj: /opt/ti/flash/f/usblib/usblib.h
blinky.obj: /opt/ti/flash/f/driverlib/uart.h
blinky.obj: ../acquire.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdio.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdarg.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdlib.h
blinky.obj: /opt/ti/flash/f/inc/hw_ints.h
blinky.obj: /media/windows/pi19404/CCS/ti/flash/f/boards/ek-lm4f232/drivers/cfal96x64x16.h
blinky.obj: /opt/ti/flash/f/utils/uartstdio.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
blinky.obj: ../flashstore.h
blinky.obj: /opt/ti/flash/f/driverlib/timer.h
blinky.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
blinky.obj: /opt/ti/flash/f/driverlib/flash.h
