acquire.obj: ../acquire.c
acquire.obj: ../acquire.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdio.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/linkage.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdarg.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdlib.h
acquire.obj: /opt/ti/flash/f/inc/hw_types.h
acquire.obj: /opt/ti/flash/f/inc/hw_memmap.h
acquire.obj: /opt/ti/flash/f/inc/hw_ints.h
acquire.obj: /opt/ti/flash/f/inc/hw_gpio.h
acquire.obj: /opt/ti/flash/f/driverlib/fpu.h
acquire.obj: /opt/ti/flash/f/driverlib/sysctl.h
acquire.obj: /opt/ti/flash/f/driverlib/rom.h
acquire.obj: /opt/ti/flash/f/driverlib/pin_map.h
acquire.obj: /opt/ti/flash/f/driverlib/gpio.h
acquire.obj: /opt/ti/flash/f/grlib/grlib.h
acquire.obj: /media/windows/pi19404/CCS/ti/flash/f/boards/ek-lm4f232/drivers/cfal96x64x16.h
acquire.obj: /opt/ti/flash/f/utils/uartstdio.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
acquire.obj: /opt/ti/flash/f/driverlib/debug.h
acquire.obj: /opt/ti/flash/f/driverlib/adc.h
acquire.obj: /opt/ti/flash/f/driverlib/hibernate.h
acquire.obj: /opt/ti/flash/f/grlib/widget.h
acquire.obj: /opt/ti/flash/f/grlib/canvas.h
acquire.obj: /opt/ti/flash/f/utils/ustdlib.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdarg.h
acquire.obj: ../qs-logger.h
acquire.obj: ../usbstick.h
acquire.obj: ../flashstore.h
acquire.obj: /opt/ti/flash/f/driverlib/timer.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
acquire.obj: /opt/ti/flash/f/driverlib/flash.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/string.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdlib.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/math.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/ymath.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/yvals.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/stdarg.h
acquire.obj: /opt/ti/ccsv5/tools/compiler/arm_5.1.1/include/_lock.h
acquire.obj: /opt/ti/flash/f/inc/hw_ssi.h
acquire.obj: /opt/ti/flash/f/driverlib/ssi.h
